In [18]:
import numpy as np
arr=np.array([[[2,3,4],[5,6,7]],[[2,3,4],[5,6,7],],[[2,3,4],[5,6,7]]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
ar=np.arange(24).reshape(6,4)
print(ar)

[[[2 3 4]
  [5 6 7]]

 [[2 3 4]
  [5 6 7]]

 [[2 3 4]
  [5 6 7]]]
(3, 2, 3)
3
18
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
(ar.resize(8,3))
print(ar)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [20]:
print(ar.dtype)

int64


In [21]:
a=np.array([[[2,3,4],[5,6,7]],[[2,3,4],[5,6,7],],[[2,3,4],[5,6,7]]],dtype=complex) 
print(a.dtype)

complex128


In [22]:
e=np.empty((2,3,4))
print(e)

[[[2.1436884e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]

 [[0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]]


In [23]:
e=np.ones((2,3),dtype=np.int16)
print(e)

[[1 1 1]
 [1 1 1]]


In [24]:
print(e.size)
print(e.shape)
print(e.ndim)

6
(2, 3)
2


In [25]:
print(np.linspace(1,2,3))
print(np.random)
p=e.flatten()
print(p)
print(np.arange(0,60,10).reshape(2,3))
l=np.random.random((2,3))
print(l)
k=np.zeros((4,5))
print(k)

[1.  1.5 2. ]
<module 'numpy.random' from '/usr/local/lib/python3.7/dist-packages/numpy/random/__init__.py'>
[1 1 1 1 1 1]
[[ 0 10 20]
 [30 40 50]]
[[0.2925254  0.19168283 0.77659915]
 [0.645485   0.86988218 0.91439512]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
